# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux dmem-filesystem routines.
#
ccflags-y += -I $(srctree)/$(src)		# needed for trace events
obj-$(CONFIG_DMEM_FS) += dmemfs.o

dmemfs-y += inode.o